import { copyRoleFiles, writeInstructionFile, buildLazyLoadingInventory } from './base.js';
import { buildRouterGuidelines } from '../router/index.js';

/**
 * Generate CHATGPT.md content optimized for ChatGPT Desktop / OpenAI Custom GPTs
 * @param {object} role 
 * @param {Array<{relativePath: string, type: string}>} files 
 * @returns {string}
 */
export function generateChatGPTInstructions(role, files) {
  let text = `# ChatGPT Desktop — STeP AI Context & System Instructions\n\n`;
  text += `**Role:** ${role.id.toUpperCase()} (${role.name || role.id}) — ${role.description || ''}\n`;
  text += `**Organization:** อุทยานวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยเชียงใหม่ (STeP / RSP North)\n`;
  text += `**Architecture Tier:** Commercial / Paid (ChatGPT Desktop / Plus / Team / Enterprise)\n`;
  text += `**Generated by:** \`step-ai\` CLI (@step-cmu/ai-harness)\n\n`;

  text += `## Core Directives & Authority Boundaries\n`;
  text += `1. **Human-in-the-loop Mandate**: You are an advisory assistant for STeP personnel. All legally binding actions, budget approvals, procurement awards, official sign-offs, and external disclosures REQUIRE explicit human staff authorization.\n`;
  text += `2. **Data Classification & Privacy**: Strictly protect CMU student/staff PII, citizen data under Thai PDPA, trade secrets of incubated startups, and private financial figures.\n`;
  text += `3. **Thai Official Standard**: Produce polite, structured, and formal Thai documentation matching CMU and Ministry of Higher Education, Science, Research and Innovation (MHESI / อว.) guidelines.\n\n`;

  text += `## 3-Layer Progressive Disclosure & Skill Router\n`;
  text += `Operates via Layer 1 Dynamic Router. Never load all organization skills into context at once.\n\n`;
  text += buildRouterGuidelines({ format: 'compact' });
  text += `\n\n`;
  text += buildLazyLoadingInventory(files);

  text += `\n## ChatGPT Best Practices for STeP Workflows\n`;
  text += `1. When drafting memos, agreements, or reports, structure output with clear headings and bullet points.\n`;
  text += `2. Verify compliance with corresponding STeP skill specifications before finalizing output.\n`;
  text += `3. Maintain strict confidentiality regarding internal projects and budgets.\n`;

  return text;
}

export function getInstructionFiles(role, files) {
  const chatGPTContent = generateChatGPTInstructions(role, files);
  return [
    { filename: 'CHATGPT.md', content: chatGPTContent },
    { filename: 'AGENTS.md', content: chatGPTContent },
  ];
}

export async function install({ workspaceDir, role, files, dryRun = false }) {
  const installedFiles = await copyRoleFiles(workspaceDir, files, dryRun);
  const instructions = getInstructionFiles(role, files);

  for (const inst of instructions) {
    const result = await writeInstructionFile(workspaceDir, inst.filename, inst.content, dryRun);
    installedFiles.push(result);
  }

  return { installedFiles, instructionsFile: 'CHATGPT.md' };
}
