import { copyRoleFiles, writeInstructionFile } from './base.js';

/**
 * Generate Codex instructions file content
 * @param {object} role 
 * @param {Array<{relativePath: string, type: string}>} files 
 * @returns {string}
 */
export function generateCodexInstructions(role, files) {
  const skillFiles = files.filter((f) => f.type === 'skill' && f.relativePath.endsWith('SKILL.md'));
  const ruleFiles = files.filter((f) => f.type === 'rule');

  let text = `# STeP AI — Codex Project Context & Instructions\n\n`;
  text += `**Role:** ${role.id.toUpperCase()} (${role.description})\n`;
  text += `**Generated by:** \`step-ai\` CLI (@step-cmu/ai-harness)\n\n`;

  text += `## มาตรฐานการทำงานของ AI สำหรับ Role นี้\n\n`;
  text += `คุณกำลังปฏิบัติงานในฐานะ AI Assistant ประจำทีม STeP / RSP North สำหรับบทบาท **${role.id}**\n`;
  text += `โปรดปฏิบัติตามกฎระเบียบและขั้นตอนการทำงานที่ได้รับอนุมัติต่อไปนี้อย่างเคร่งครัด:\n\n`;

  text += `### 1. กติกากลางด้านความปลอดภัย (Mandatory Rules)\n\n`;
  for (const r of ruleFiles) {
    text += `- [${r.relativePath}](${r.relativePath})\n`;
  }
  text += `- ข้อมูลส่วนบุคคล สัญญา งบประมาณ และเอกสารต้นฉบับที่จำกัดการเข้าถึงต้องไม่ถูก commit หรือเปิดเผย\n`;
  text += `- การกระทำที่มีผลในโลกจริง (เช่น ส่งหนังสือ ส่งงาน อนุมัติงบ) ต้องผ่านการอนุมัติโดยมนุษย์เสมอ\n\n`;

  text += `### 2. Approved Skills ประจำบทบาท\n\n`;
  for (const s of skillFiles) {
    const skillName = s.relativePath.split('/')[2];
    text += `- **${skillName}**: ดูวิธีทำงานและขั้นตอนใน [${s.relativePath}](${s.relativePath})\n`;
  }

  text += `\n### 3. คำแนะนำในการเรียกใช้\n`;
  text += `- เมื่อได้รับมอบหมายงาน ให้ตรวจดูว่าตรงกับขอบเขตของ Skill ใด แล้วปฏิบัติตามเงื่อนไข ขั้นตอน และเกณฑ์จบงานใน Skill นั้น\n`;
  text += `- หากข้อมูลที่ได้รับไม่ครบถ้วนและทำให้สาระสำคัญเปลี่ยน ให้ระบุว่าเป็นข้อมูล "รอยืนยัน" หรือสอบถามเจ้าของงาน\n`;

  return text;
}

export function getInstructionFiles(role, files) {
  const content = generateCodexInstructions(role, files);
  return [
    { filename: 'CODEX_INSTRUCTIONS.md', content },
    { filename: 'AGENTS.md', content },
  ];
}

export async function install({ workspaceDir, role, files, dryRun = false }) {
  const installedFiles = await copyRoleFiles(workspaceDir, files, dryRun);
  const instructions = getInstructionFiles(role, files);

  for (const inst of instructions) {
    const result = await writeInstructionFile(workspaceDir, inst.filename, inst.content, dryRun);
    installedFiles.push(result);
  }

  return { installedFiles, instructionsFile: 'CODEX_INSTRUCTIONS.md' };
}
