import { copyRoleFiles, writeInstructionFile, buildLazyLoadingInventory, buildFirstWorkOnboardingContract } from './base.js';
import { buildRouterGuidelines } from '../router/index.js';

/**
 * Generate Codex instructions file content
 * @param {object} role 
 * @param {Array<{relativePath: string, type: string}>} files 
 * @returns {string}
 */
export function generateCodexInstructions(role, files) {
  let text = `# STeP AI — Codex Project Context & Instructions\n\n`;
  text += `**Role:** ${role.id.toUpperCase()} (${role.description})\n`;
  text += `**Organization:** อุทยานวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยเชียงใหม่ (STeP / RSP North - 22 Teams)\n`;
  text += `**Generated by:** \`step-ai\` CLI (@step-cmu/ai-harness)\n\n`;

  text += `## มาตรฐานการทำงานของ AI สำหรับบริบทนี้\n\n`;
  text += `คุณกำลังปฏิบัติงานในฐานะ AI Assistant ประจำองค์กร STeP / RSP North สำหรับ **${role.id}**\n`;
  text += `โปรดปฏิบัติตามกฎระเบียบและขั้นตอนการทำงานที่ได้รับอนุมัติต่อไปนี้อย่างเคร่งครัด:\n\n`;

  text += `### 1. กติกากลางด้านความปลอดภัย\n\n`;
  text += `- ข้อมูลส่วนบุคคล สัญญา งบประมาณ Credential และเอกสารจำกัดการเข้าถึงต้องไม่ถูก commit หรือเปิดเผย\n`;
  text += `- การกระทำที่มีผลในโลกจริง (เช่น ส่งหนังสือ ส่งงาน อนุมัติงบ) ต้องผ่านการอนุมัติโดยมนุษย์เสมอ\n`;
  text += `- อย่าอ่าน Rules ทั้งโฟลเดอร์ตอนเริ่มต้น ให้โหลดเฉพาะ mandatory references ของ Skill ที่ Router เลือกเมื่อมีงานจริง\n\n`;

  text += `### 2. สถาปัตยกรรม 3 ชั้นและ Progressive Disclosure\n\n`;
  text += buildRouterGuidelines({ format: 'compact' });
  text += `\n`;
  text += buildLazyLoadingInventory(files);
  text += buildFirstWorkOnboardingContract(role);

  text += `\n### 5. คำแนะนำในการเรียกใช้\n`;
  text += `- เมื่อได้รับมอบหมายงาน ให้ตรวจดูว่าตรงกับขอบเขตของ Skill ใด แล้วปฏิบัติตามเงื่อนไข ขั้นตอน และเกณฑ์จบงานใน Skill นั้น\n`;
  text += `- หากข้อมูลที่ได้รับไม่ครบถ้วนและทำให้สาระสำคัญเปลี่ยน ให้ระบุว่าเป็นข้อมูล "รอยืนยัน" หรือสอบถามเจ้าของงาน\n`;

  return text;
}

export function getInstructionFiles(role, files) {
  const content = generateCodexInstructions(role, files);
  return [
    { filename: 'CODEX_INSTRUCTIONS.md', content },
    { filename: 'AGENTS.md', content },
  ];
}

export async function install({ workspaceDir, role, files, dryRun = false }) {
  const installedFiles = await copyRoleFiles(workspaceDir, files, dryRun);
  const instructions = getInstructionFiles(role, files);

  for (const inst of instructions) {
    const result = await writeInstructionFile(workspaceDir, inst.filename, inst.content, dryRun);
    installedFiles.push(result);
  }

  return { installedFiles, instructionsFile: 'CODEX_INSTRUCTIONS.md' };
}
