import { copyRoleFiles, writeInstructionFile, buildLazyLoadingInventory } from './base.js';
import { buildRouterGuidelines } from '../router/index.js';

/**
 * Generate GEMINI.md content optimized for Google Antigravity & Spark / Gemini
 * @param {object} role 
 * @param {Array<{relativePath: string, type: string}>} files 
 * @returns {string}
 */
export function generateGeminiInstructions(role, files) {
  let text = `# Google Antigravity & Spark — STeP AI Context & Instructions\n\n`;
  text += `**Role:** ${role.id.toUpperCase()} (${role.name || role.id}) — ${role.description || ''}\n`;
  text += `**Organization:** อุทยานวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยเชียงใหม่ (STeP / RSP North)\n`;
  text += `**Architecture Tier:** Commercial / Paid (Google Antigravity / Google Spark / Gemini Enterprise)\n`;
  text += `**Generated by:** \`step-ai\` CLI (@step-cmu/ai-harness)\n\n`;

  text += `## Core Directives & Authority Boundaries\n`;
  text += `1. **Human-in-the-loop Mandate**: You are an advisory assistant for STeP personnel. All legally binding actions, budget approvals, procurement awards, official sign-offs, and external disclosures REQUIRE explicit human staff authorization.\n`;
  text += `2. **Data Classification & Privacy**: Strictly protect CMU student/staff PII, citizen data under Thai PDPA, trade secrets of incubated startups, and private financial figures.\n`;
  text += `3. **Thai Official Standard**: Produce polite, structured, and formal Thai documentation matching CMU and Ministry of Higher Education, Science, Research and Innovation (MHESI / อว.) guidelines.\n\n`;

  text += `## 3-Layer Progressive Disclosure & Skill Router\n`;
  text += `Operates via Layer 1 Dynamic Router. Never load all organization skills into context at once.\n\n`;
  text += buildRouterGuidelines();
  text += `\n\n`;
  text += buildLazyLoadingInventory(files);

  text += `\n## Google Antigravity & Spark Execution Directives\n`;
  text += `1. Follow task management and planning guidelines before modifying project artifacts.\n`;
  text += `2. Adhere to Thai administrative formatting for CMU/STeP official memos and TOR documents.\n`;
  text += `3. Leverage progressive tool discovery to retrieve specific skills as requested by the user.\n`;

  return text;
}

export function getInstructionFiles(role, files) {
  const geminiContent = generateGeminiInstructions(role, files);
  return [
    { filename: 'GEMINI.md', content: geminiContent },
    { filename: 'AGENTS.md', content: geminiContent },
  ];
}

export async function install({ workspaceDir, role, files, dryRun = false }) {
  const installedFiles = await copyRoleFiles(workspaceDir, files, dryRun);
  const instructions = getInstructionFiles(role, files);

  for (const inst of instructions) {
    const result = await writeInstructionFile(workspaceDir, inst.filename, inst.content, dryRun);
    installedFiles.push(result);
  }

  return { installedFiles, instructionsFile: 'GEMINI.md' };
}
