import { copyRoleFiles, writeInstructionFile } from './base.js';
import { buildRouterGuidelines } from '../router/index.js';

/**
 * Generate OPENCODE.md content optimized for OpenCode AI Assistant (Free Quota Tier)
 * @param {object} role 
 * @param {Array<{relativePath: string, type: string}>} files 
 * @returns {string}
 */
export function generateOpenCodeInstructions(role, files) {
  const skillFiles = files.filter((f) => f.type === 'skill' && f.relativePath.endsWith('SKILL.md'));
  const ruleFiles = files.filter((f) => f.type === 'rule');

  let text = `# OpenCode AI Assistant — STeP AI Context & Instructions\n\n`;
  text += `**Role:** ${role.id.toUpperCase()} (${role.name || role.id}) — ${role.description || ''}\n`;
  text += `**Organization:** อุทยานวิทยาศาสตร์และเทคโนโลยี มหาวิทยาลัยเชียงใหม่ (STeP / RSP North)\n`;
  text += `**Architecture Tier:** Free Quota AI Assistant (OpenCode / Free Tier)\n`;
  text += `**Generated by:** \`step-ai\` CLI (@step-cmu/ai-harness)\n\n`;

  text += `## Core Directives & Authority Boundaries\n`;
  text += `1. **Human-in-the-loop Mandate**: You are an advisory assistant for STeP personnel. All legally binding actions, budget approvals, procurement awards, official sign-offs, and external disclosures REQUIRE explicit human staff authorization.\n`;
  text += `2. **Data Classification & Privacy**: Strictly protect CMU student/staff PII, citizen data under Thai PDPA, trade secrets of incubated startups, and private financial figures.\n`;
  text += `3. **Thai Official Standard**: Produce polite, structured, and formal Thai documentation matching CMU and Ministry of Higher Education, Science, Research and Innovation (MHESI / อว.) guidelines.\n\n`;

  text += `## 3-Layer Progressive Disclosure & Skill Router\n`;
  text += `OpenCode operates with Layer 1 Dynamic Router. Never load all organization skills into context at once.\n\n`;
  text += buildRouterGuidelines();
  text += `\n\n`;

  text += `## Active Organization Rules\n`;
  for (const r of ruleFiles) {
    text += `- [Rule] ${r.relativePath}: Read and enforce strictly.\n`;
  }

  text += `\n## Approved Organization Skills for Team ${role.id.toUpperCase()}\n`;
  for (const s of skillFiles) {
    const parts = s.relativePath.split('/');
    const skillName = parts.length >= 3 ? parts[2] : s.relativePath;
    text += `- **${skillName}**: Reference file at \`${s.relativePath}\`\n`;
  }

  text += `\n## OpenCode Best Practices for STeP Workflows\n`;
  text += `1. Analyze user intent and identify appropriate skill before answering.\n`;
  text += `2. Read corresponding SKILL.md before providing detailed procedures.\n`;
  text += `3. Keep answers focused, practical, and compliant with STeP regulations.\n`;

  return text;
}

export function getInstructionFiles(role, files) {
  const openCodeContent = generateOpenCodeInstructions(role, files);
  return [
    { filename: 'OPENCODE.md', content: openCodeContent },
    { filename: 'AGENTS.md', content: openCodeContent },
  ];
}

export async function install({ workspaceDir, role, files, dryRun = false }) {
  const installedFiles = await copyRoleFiles(workspaceDir, files, dryRun);
  const instructions = getInstructionFiles(role, files);

  for (const inst of instructions) {
    const result = await writeInstructionFile(workspaceDir, inst.filename, inst.content, dryRun);
    installedFiles.push(result);
  }

  return { installedFiles, instructionsFile: 'OPENCODE.md' };
}
